#!/bin/bash

## Copyright (C) 2012 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
shopt -s inherit_errexit
shopt -s shift_verbose
export LC_ALL=C

cache_folder="/var/cache/anon-base-files"

if test -f /run/qubes/this-is-templatevm ; then
   ## Separate done file for Qubes TemplateVMs to make this work with the
   ## current home folder population for Qubes DispVMs.
   ## https://github.com/QubesOS/qubes-core-agent-linux/blob/f380c346cf9af3f058b8ece853d7d4a5ece28815/misc/dispvm-prerun.sh#L6-L12
   done_file="${cache_folder}/first-boot-skel.TemplateVM.done"
else
   ## Non-Qubes-Whonix or non-Qubes TemplateVMs
   done_file="${cache_folder}/first-boot-skel.done"
fi

if [ "${1:-}" = "force" ]; then
   safe-rm --force -- "${done_file}"
fi

if [ -e "${done_file}" ]; then
   exit 0
fi

user_name="user"
home_dir="/home/${user_name}"

if [ ! -d "${home_dir}" ]; then
   exit 0
fi

skel_folder="/etc/skel"

if [ ! -d "${skel_folder}" ]; then
   exit 0
fi

pushd "${skel_folder}"

mkdir -p "${cache_folder}"

shopt -s dotglob
shopt -s nullglob

for fso in ./* ; do
   true "fso: ${fso}"
   ## Technically below for 'cp' it would also be possible to use '$fso' rather
   ## than '$fso_basename', but the latter produces a prettier xtrace.
   fso_basename="${fso##*/}"
   if [ -d "${fso}" ]; then
      true "folder: yes"
      cp --verbose --no-clobber --archive --parents --recursive "${fso_basename}" "${home_dir}"
      chown --changes --recursive "${user_name}:${user_name}" "${home_dir}/${fso_basename}"
   else
      true "folder: no"
      ## Require '--dereference' otherwise the 'chown' below could fail.
      cp --verbose --no-clobber --archive --dereference "${fso_basename}" "${home_dir}"
      chown --changes "${user_name}:${user_name}" "${home_dir}/${fso_basename}"
   fi
done

touch "${done_file}"
